version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: foot
    ports:
      - "5432:5432"

  spring-application-back:
    build:
      context: ./come2play
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/foot?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  angular-application-front:
    build:
      context: ./come2play-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:88"
    depends_on:
      - spring-application-back

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
